#!/usr/bin/env bash
#
#   TODO: add Kerberos support
#
#   Installing CDH4 with MRv1 on a Single Linux Node in Pseudo-distributed mode 
#   http://www.cloudera.com/content/cloudera/en/documentation/cdh4/latest/CDH4-Quick-Start/cdh4qs_topic_3_2.html
#

# load service functions

. ${RERUN_MODULE_DIR}/lib/service-functions.sh

usage() {

    [ -z ${RERUN_COMMAND_DIR} ] && {
        echo "usage: ${0} <options>"
    } || {
        echo "usage: ./rerun cdh-deploy:config-cdh4-pseudo-single-node-base <options>"
    }
    echo "    --run:    run configuration of CDH4 Pseudo distributed Single node cluster (Base)"
    [ ! -z ${RERUN_COMMAND_DIR} ] && {
        echo "    --export-to=<directory>: export config script to <directory>"
        echo 
        echo "Note: only one option can be defined"
    }
    echo
}


namenode_format() {
    
    echo "- NameNode formatting ..."
    sudo -u hdfs hdfs namenode -format && {
        echo "- NameNode formatting is completed"
    } || {
        echo "Error! NameNode formatting is failed"
        exit 1
    }
}

start_hdfs_service() {

    echo "- Starting HDFS services ..."
    for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do 
        sudo service $x start ; 
    done
    check_java_process namenode
    check_java_process secondarynamenode
    check_java_process datanode
}

create_mapreduce_dirs() {

    echo "- Creating /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
    echo "- Changing rights for /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
        sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred && \
    {
        echo "- The MapReduce system directories are created successfully"
    } || {
        echo "Error! The MapReduce system directories were not created"    
        exit 1
    }
}

start_mapreduce() {

    for x in `cd /etc/init.d ; ls hadoop-0.20-mapreduce-*` ; do sudo service $x start ; done

    check_java_process jobtracker
    check_java_process tasktracker
}

config() {

    # Format the NameNode
    namenode_format

    # Start HDFS
    start_hdfs_service

    # Create the /tmp directory 
    sudo -u hdfs hadoop fs -mkdir /tmp && sudo -u hdfs hadoop fs -chmod -R 1777 /tmp

    # Create the MapReduce system directories
    create_mapreduce_dirs

    # Start MapReduce 
    start_mapreduce

    # Create User Directories 
    echo "- Creating default directory: /user/cloudera/"
    sudo -u hdfs hadoop fs -mkdir /user/cloudera && \
        sudo -u hdfs hadoop fs -chown cloudera /user/cloudera/    
}

# ==============================================
#   Main script
# ----------------------------------------------
handle_command_options "$@"
