#!/usr/bin/env bash
#
#   TODO: add Kerberos support
#
#   Installing CDH4 with MRv1 on a Single Linux Node in Pseudo-distributed mode 
#   http://www.cloudera.com/content/cloudera/en/documentation/cdh4/latest/CDH4-Quick-Start/cdh4qs_topic_3_2.html
#
RUNLEVEL="rc2"

. ${RERUN_MODULES%%/}/lib/service-functions.sh     


usage() {

    [ -z ${RERUN_COMMAND_DIR} ] && {
        echo "usage: ${0} <options>"
    } || {
        echo "usage: ./rerun config:hdfs <options>"
    }
    echo "    --run:    run basic HDFS configuration of CDH4 Pseudo distributed Single node cluster"
    [ ! -z ${RERUN_COMMAND_DIR} ] && {
        echo "    --export-to <directory>: export config script to <directory>"
        echo 
        echo "Note: only one option can be defined"
    }
    echo
}

create_mapreduce_dirs() {

    echo "- Creating /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
    echo "- Changing rights for /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
        sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred && \
    {
        echo "- The MapReduce system directories are created successfully"
    } || {
        echo "Error! The MapReduce system directories were not created"    
        exit 1
    }
}

start_mapreduce() {

    for x in `cd /etc/init.d ; ls hadoop-0.20-mapreduce-*`
    do 
        sudo service $x start
    done

    check_java_process jobtracker
    check_java_process tasktracker
}

run() {

    # Create the MapReduce system directories
    create_mapreduce_dirs

    # Start MapReduce 
    start_mapreduce
}

# ==============================================
#   Main script
# ----------------------------------------------
handle_command_options "$@"

