#!/usr/bin/env bash

usage() {

    echo "usage: ./rerun verify:cdh-base <options>"
    echo
}

verify_hadoop_pseudo_conf_package() {

    echo -n "- Verifying the hadoop-0.20-conf-pseudo package: "
    dpkg -L hadoop-0.20-conf-pseudo 2> /dev/null && {
        echo "- Verification result: SUCCESS"
    } || {
        echo "- Verification result: FAIL"
        exit 1
    }
}

verify_hadoop_pseudo_conf_package
