#!/usr/bin/env bash

TAGS=${1}

#
#   usage
#
usage() {

    echo "usage: ./rerun install:dockerfile <tags>"
    echo
}


list_available_components() {

    ls ${RERUN_COMMAND_DIR%%/}/components/*.dockerfile
}



[ -z ${TAGS} ] && {
    usage

    echo -n "List of available components: "
    for component in $(list_available_components)
    do
        echo -n "$(basename ${component} .dockerfile) "
    done
    echo
    exit 1
}

cat ${RERUN_COMMAND_DIR%%/}/templates/header.dockerfile

for component in $(echo ${TAGS} | tr "," "\n")
do
    [ -f ${RERUN_COMMAND_DIR%%/}/components/${component}.dockerfile ] && {
        cat ${RERUN_COMMAND_DIR%%/}/components/${component}.dockerfile
    }
done

cat ${RERUN_COMMAND_DIR%%/}/templates/footer.dockerfile

